/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import Controller.ProductosJpaController;
import Controller.IngredientesprincipalesJpaController;

import Entities.Empleados;
import Entities.Productos;
import Entities.Ingredientesprincipales;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import java.text.SimpleDateFormat;
import java.util.Date;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author gpera
 */
public class PanelInventario extends javax.swing.JPanel {

    ProductosJpaController ctrproductos = new ProductosJpaController();
    Productos producto = new Productos();

    IngredientesprincipalesJpaController ctringredientesprincipales = new IngredientesprincipalesJpaController();
    Ingredientesprincipales ingrediente = new Ingredientesprincipales();

    public PanelInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        BTNuevo = new javax.swing.JButton();
        BTGuardar = new javax.swing.JButton();
        BTEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFIdProducto = new javax.swing.JTextField();
        TFNombreProducto = new javax.swing.JTextField();
        TFTipoProducto = new javax.swing.JTextField();
        TFFechaProduccion = new javax.swing.JTextField();
        TFFechaExpiracion = new javax.swing.JTextField();
        TFPrecio = new javax.swing.JTextField();
        TFIdIngredientePrincipal = new javax.swing.JTextField();

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setText("Este es el panel inventario");

        jtInventario.setBackground(new java.awt.Color(204, 204, 204));
        jtInventario.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jtInventario.setForeground(new java.awt.Color(0, 0, 0));
        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtInventario.setToolTipText("");
        jtInventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtInventario.setMaximumSize(new java.awt.Dimension(60, 64));
        jtInventario.setRowHeight(30);
        jScrollPane1.setViewportView(jtInventario);

        BTNuevo.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        BTNuevo.setText("Nuevo");
        BTNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNuevoActionPerformed(evt);
            }
        });

        BTGuardar.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        BTGuardar.setText("Guardar");
        BTGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTGuardarActionPerformed(evt);
            }
        });

        BTEditar.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        BTEditar.setText("Editar");
        BTEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEditarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Producto");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Producto");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo Producto");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha Produccion");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha Expiracion");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Precio");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ID Ingrediente Principal");

        TFIdProducto.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        TFIdProducto.setEnabled(false);

        TFNombreProducto.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TFTipoProducto.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TFFechaProduccion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TFFechaExpiracion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TFPrecio.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TFIdIngredientePrincipal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFFechaProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFIdIngredientePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 97, Short.MAX_VALUE)
                        .addComponent(BTNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BTEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BTGuardar)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(TFIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFIdIngredientePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFFechaProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TFFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTGuardarActionPerformed
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");

            producto.setNombreProducto(TFNombreProducto.getText());
            producto.setTipoProducto(TFTipoProducto.getText());
            producto.setFechaProduccion(formatoFecha.parse(TFFechaProduccion.getText()));
            producto.setFechaExpiracion(formatoFecha.parse(TFFechaExpiracion.getText()));
            producto.setPrecio(Float.parseFloat(TFPrecio.getText()));
            ingrediente.setIdIngredientePrincipal(Integer.parseInt(TFIdIngredientePrincipal.getText()));

            ctrproductos.create(producto);

            bloquearControles();
            JOptionPane.showMessageDialog(null, "Producto guardado correctamente");
            rellenarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "Error");
        }

    }// GEN-LAST:event_BTGuardarActionPerformed

    private void BTEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTEditarActionPerformed
        //hacer el metodo para editar parecido al de empleados
        try {
                        
            if (TFIdProducto.getText().trim().isEmpty() || !TFIdProducto.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "ID de empleado inválido.");
                return;
            }

            if (TFNombreProducto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nombre de producto inválido.");
                return;
            }

            if (TFTipoProducto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tipo de producto inválido.");
                return;
            }

            if (TFFechaProduccion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Fecha de producción inválida.");
                return;
            }

            if (TFFechaExpiracion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Fecha de expiración inválida.");
                return;
            }

            if (TFPrecio.getText().trim().isEmpty() || !TFPrecio.getText().matches("\\d+(\\.\\d+)?")) {
                JOptionPane.showMessageDialog(null, "Precio inválido.");
                return;
            }

            if (TFIdIngredientePrincipal.getText().trim().isEmpty() || !TFIdIngredientePrincipal.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "ID de ingrediente principal inválido.");
                return;
            }

            producto.setIdProducto(Integer.parseInt(TFIdProducto.getText()));
            producto.setNombreProducto(TFNombreProducto.getText());
            producto.setTipoProducto(TFTipoProducto.getText());
            producto.setFechaProduccion(new SimpleDateFormat("yyyy-MM-dd").parse(TFFechaProduccion.getText()));
            producto.setFechaExpiracion(new SimpleDateFormat("yyyy-MM-dd").parse(TFFechaExpiracion.getText()));
            producto.setPrecio(Float.parseFloat(TFPrecio.getText()));
            ingrediente.setIdIngredientePrincipal(Integer.parseInt(TFIdIngredientePrincipal.getText()));
            producto.setIdIngredientePrincipal(ingrediente);

            updateProducto(producto);
            updateIdIngredientePrincipal(ingrediente);


            bloquearControles();
            JOptionPane.showMessageDialog(null, "Editado Correctamente");
            rellenarTabla();

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + " Error");
        }
    }

    public void updateProducto(Productos producto) {
        String sql = "UPDATE productos SET nombreProducto=?, tipoProducto=?, fechaProduccion=?, fechaExpiracion=?, precio=?, idIngredientePrincipal=? WHERE idProducto=?";
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/medicinanatural", "root",
                "rootsito");
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, producto.getNombreProducto());
            pstmt.setString(2, producto.getTipoProducto());
            pstmt.setDate(3, new java.sql.Date(producto.getFechaProduccion().getTime()));
            pstmt.setDate(4, new java.sql.Date(producto.getFechaExpiracion().getTime()));
            pstmt.setFloat(5, producto.getPrecio());
            pstmt.setInt(6, producto.getIdIngredientePrincipal().getIdIngredientePrincipal());
            pstmt.setInt(7, producto.getIdProducto());

            pstmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    public void updateIdIngredientePrincipal(Ingredientesprincipales ingrediente) {
        String sql = "UPDATE ingredientesprincipales SET idIngredientePrincipal=? WHERE idIngredientePrincipal=?";
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/medicinanatural", "root",
                "rootsito");
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, ingrediente.getIdIngredientePrincipal());
            pstmt.setInt(2, ingrediente.getIdIngredientePrincipal());

            pstmt.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

       
    // GEN-LAST:event_BTEditarActionPerformed

    private void BTNuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTNuevoActionPerformed
        activarEditar();
        TFIdProducto.setText("");
        TFNombreProducto.setText("");
        TFTipoProducto.setText("");
        TFFechaProduccion.setText("");
        TFFechaExpiracion.setText("");
        TFPrecio.setText("");
        TFIdIngredientePrincipal.setText("");
    }// GEN-LAST:event_BTNuevoActionPerformed

    // Metodo para bloquear controles
    public void bloquearControles() {
        TFIdProducto.setEnabled(false);
        TFNombreProducto.setEnabled(false);
        TFTipoProducto.setEnabled(false);
        TFFechaProduccion.setEnabled(false);
        TFFechaExpiracion.setEnabled(false);
        TFPrecio.setEnabled(false);
        TFIdIngredientePrincipal.setEnabled(false);
    }

    public void activarEditar() {
        TFIdProducto.setEnabled(true);
        TFNombreProducto.setEnabled(true);
        TFTipoProducto.setEnabled(true);
        TFFechaProduccion.setEnabled(true);
        TFFechaExpiracion.setEnabled(true);
        TFPrecio.setEnabled(true);
        TFIdIngredientePrincipal.setEnabled(true);
    }

    public void rellenarTabla() {
        String columna[] = {"ID Producto", "Nombre Producto", "Tipo Producto", "Fecha Produccion", "Caduca",
            "Precio", "ID Ingrediente Principal"};
        DefaultTableModel modelo = new DefaultTableModel(columna, 0);
        Object[] obj = new Object[7];
        List<Productos> ls;
        try {
            ls = ctrproductos.findProductosEntities();
            for (Productos producto : ls) {
                obj[0] = producto.getIdProducto();
                obj[1] = producto.getNombreProducto();
                obj[2] = producto.getTipoProducto();
                obj[3] = producto.getFechaProduccion();
                obj[4] = producto.getFechaExpiracion();
                obj[5] = producto.getPrecio();
                // Verificar si idIngredientePrincipal es null antes de acceder a él
                obj[6] = producto.getIdIngredientePrincipal() != null ? producto.getIdIngredientePrincipal().getIdIngredientePrincipal() : "N/A";
    
                modelo.addRow(obj);
            }
    
            jtInventario.setModel(modelo);
            jtInventario.setAutoCreateRowSorter(true);
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
            jtInventario.setRowSorter(sorter);
    
            // Mover MouseListener fuera del bucle
            jtInventario.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent mouseEvent) {
                    if (mouseEvent.getClickCount() == 2) {
                        TFIdProducto.setText(jtInventario.getValueAt(jtInventario.getSelectedRow(), 0).toString());
                        TFNombreProducto.setText(jtInventario.getValueAt(jtInventario.getSelectedRow(), 1).toString());
                        TFTipoProducto.setText(jtInventario.getValueAt(jtInventario.getSelectedRow(), 2).toString());
                        TFFechaProduccion.setText(jtInventario.getValueAt(jtInventario.getSelectedRow(), 3).toString());
                        TFFechaExpiracion.setText(jtInventario.getValueAt(jtInventario.getSelectedRow(), 4).toString());
                        TFPrecio.setText(jtInventario.getValueAt(jtInventario.getSelectedRow(), 5).toString());
                        TFIdIngredientePrincipal.setText(jtInventario.getValueAt(jtInventario.getSelectedRow(), 6).toString());
    
                        activarEditar();
                    }
                }
            });
    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + " Error");
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTEditar;
    private javax.swing.JButton BTGuardar;
    private javax.swing.JButton BTNuevo;
    private javax.swing.JTextField TFFechaExpiracion;
    private javax.swing.JTextField TFFechaProduccion;
    private javax.swing.JTextField TFIdIngredientePrincipal;
    private javax.swing.JTextField TFIdProducto;
    private javax.swing.JTextField TFNombreProducto;
    private javax.swing.JTextField TFPrecio;
    private javax.swing.JTextField TFTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jtInventario;
    // End of variables declaration//GEN-END:variables
}
