/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFrame;

import Frames.PanelEmpleados;
import principal.EventMenuSeleccionado;
import principal.Model_Menu;


public class Menu extends javax.swing.JPanel {

    private EventMenuSeleccionado event;

    public void addEvent(EventMenuSeleccionado event) {
        this.event = event;
    }

    public Menu() {
        initComponents();
        setOpaque(false);
        init();
    }
    private JFrame Main;

    public Menu(JFrame Main) {
        this.Main = Main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMenu1 = new principal.ListMenu<>();

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jScrollPane1.setViewportView(listMenu1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {
        PanelEmpleados panelEmpleados = new PanelEmpleados();
        Main.getContentPane().add(panelEmpleados);
        Main.revalidate();
        Main.repaint();

    }

    private void ISalirMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ISalirMouseClicked
        System.exit(0);
    }// GEN-LAST:event_ISalirMouseClicked

    private void init() {
        listMenu1.addItem(new Model_Menu("1", "Empleados",
        Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("2", "UI Elements",
        // Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("3", "Comonents",
        // Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("4", "Forms Stuff",
        // Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("5", "Date Table",
        // Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));

        // listMenu1.addItem(new Model_Menu("", "My Data", Model_Menu.MenuType.TITLE));
        // listMenu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));
        // listMenu1.addItem(new Model_Menu("6", "Icons", Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("7", "Sample Page",
        // Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("8", "Extra", Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("9", "More", Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("10", "Logout", Model_Menu.MenuType.MENU));
        // listMenu1.addItem(new Model_Menu("", "", Model_Menu.MenuType.EMPTY));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private principal.ListMenu<String> listMenu1;
    // End of variables declaration//GEN-END:variables
}
